// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathfinderSecondEdition;

#nullable disable

namespace PathfinderSecondEdition.Migrations
{
    [DbContext(typeof(CharacterSheetDbContext))]
    [Migration("20250106093820_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PathfinderSecondEdition.AbilityScore", b =>
                {
                    b.Property<int>("AbilityScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterSheetModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("AbilityScoreId");

                    b.HasIndex("CharacterSheetModelId")
                        .IsUnique();

                    b.ToTable("AbilityScores");
                });

            modelBuilder.Entity("PathfinderSecondEdition.CharacterSheetModel", b =>
                {
                    b.Property<int>("CharacterSheetModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHP")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterSheetModelId");

                    b.ToTable("CharacterSheetModels");
                });

            modelBuilder.Entity("PathfinderSecondEdition.AbilityScore", b =>
                {
                    b.HasOne("PathfinderSecondEdition.CharacterSheetModel", "CharacterSheetModel")
                        .WithOne("AbilityScore")
                        .HasForeignKey("PathfinderSecondEdition.AbilityScore", "CharacterSheetModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSheetModel");
                });

            modelBuilder.Entity("PathfinderSecondEdition.CharacterSheetModel", b =>
                {
                    b.Navigation("AbilityScore")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
